apiVersion: v1
description: DEPRECATED - A Helm chart to install an openvpn server inside a kubernetes cluster.  Certificate
  generation is also part of the deployment, and this chart will generate client keys
  as needed.
name: openvpn-ncp
version: 1.0
appVersion: 1.1.0
deprecated: true
icon: https://forums.openvpn.net/styles/openvpn/theme/images/ovpnlogo.png
keywords:
- openvpn
- vpn
- tunnel
- network
- service
- connectivity
- encryption
home: https://openvpn.net/index.php/open-source.html
sources:
- https://github.com/jfelten/openvpn-docker
- https://github.com/kubernetes/charts/tree/master/stable/openvpn
- https://github.com/jfelten/helm-charts
- http://192.168.252.251:30040/release/cns-core-images/src/branch/develop/docker/open5gs/openvpn/Dockerfile
