# Default values for openvpn.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

updateStrategy: {}
  # type: RollingUpdate
  # rollingUpdate:
  #   maxSurge: 1
  #   maxUnavailable: 0

# For supporting pulling from private registries
imagePullSecretName: ncp-secret
route:
  interface: server
  spirent: 120.120.0.0/16
  upfn4: 4.4.72.0/24
image:
  repository: cnscore-registry.kr.ncr.ntruss.com/open5gs
  tag: v2.6.1_openvpn
  pullPolicy: IfNotPresent
service:
  type: NodePort #LoadBalancer
  externalPort: 443
  internalPort: 443
  # hostPort: 443
  externalIPs: []
  nodePort: 32444
  lab_public_ip: 192.168.252.72
  # clusterIP: None
  # LoadBalancerSourceRanges: 0.0.0.0/0
  # loadBalancerIP: 10.0.0.1

  ## Here annotations can be added to the openvpn service
  # annotations:
  #   external-dns.alpha.kubernetes.io/hostname: vpn.example.com
  annotations: {}
## Here annotations can be added to the openvpn pod
# podAnnotations:
#   backup.ark.heptio.com/backup-volumes: certs
#   interface name must be same to above route.interface
#   You have to make "openvpn-datanet" CRD first in the namespace.
podAnnotations: {k8s.v1.cni.cncf.io/networks: ' [{ "name": "openvpn-datanet", "ips": [ "9.9.72.6/24" ], "interface": "server" }]'}

# Add privileged init container to enable IPv4 forwarding
ipForwardInitContainer: true

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 500m
    memory: 128Mi

readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 5
  successThreshold: 2

persistence:
  enabled: false
  # subPath: openvpn
  ## A manually managed Persistent Volume and Claim
  ## Requires persistence.enabled: true
  ## If defined, PVC must be created manually before volume will be bound
  # existingClaim:

  ## openvpn data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  storageClass: "nfs-client"
  accessMode: ReadWriteOnce
  size: 1Gi
openvpn:
  # Network allocated for openvpn clients (default: 10.240.0.0).
  OVPN_NETWORK: 192.168.72.0
  # Network subnet allocated for openvpn client (default: 255.255.0.0).
  OVPN_SUBNET: 255.255.255.0
  # Protocol used by openvpn tcp or udp (default: udp).
  OVPN_PROTO: udp
  # Kubernetes pod network (optional).
  OVPN_K8S_POD_NETWORK: "172.16.0.0"
  # Kubernetes pod network subnet (optional).
  OVPN_K8S_POD_SUBNET: "255.255.255.0"
  # Kubernetes service network (optional).
  # Define openvpn.OVPN_K8S_SVC_NETWORK and openvpn.OVPN_K8S_SVC_SUBNET if it's needed to create a separate route to Kubernates service subnet
  OVPN_K8S_SVC_NETWORK:  "10.96.0.0"
  # Kubernetes service network subnet (optional).
  OVPN_K8S_SVC_SUBNET: "255.240.0.0"
  # Set default route which openvpn figures basing on network routes inside openvpn pod
  DEFAULT_ROUTE_ENABLED: true
  # Server certificate data
  # keystoreSecret:
  # secret with openvpn certificates. If specified, certificates are taken from the secret
  # create secret with such command:
  #    kubectl create secret generic openvpn-keystore-secret --from-file=./server.key --from-file=./ca.crt --from-file=./server.crt --from-file=./dh.pem [--from-file=./crl.pem]  [--from-file=./ta.key]
  # Push a `dhcp-option DOMAIN` config
  dhcpOptionDomain: true
  # Redirect all client traffic through VPN
  redirectGateway: false
  # Use/generate certificate revocation list
  useCrl: false
  # Use/generate a ta.key (https://openvpn.net/community-resources/hardening-openvpn-security/)
  taKey: false
  # Override default cipher
  cipher: AES-256-GCM 
  # Lines appended to the end of the server configuration file
  serverConf: |
    client-to-client
    route 198.18.0.0 255.255.255.0 # client site cidr
    route 198.19.128.0 255.255.240.0 # client site cidr
    route 172.22.0.0 255.255.255.0
    push "route 120.120.0.0 255.255.0.0" # server site cidr
    push "route 4.4.72.0 255.255.255.0" # server site cidr



  # Lines appended to the end of the client configuration file
  # Example: if all of your clients are Ubuntu (18.04+) you may need to install
  # the update-systemd-resolved package (apt install update-systemd-resolved) then
  # set the following to make sure systemd-resolved routes DNS requests correctly:
  # clientConf: |
  #  script-security 2
  #  up /etc/openvpn/update-systemd-resolved
  #  up-restart
  #  down /etc/openvpn/update-systemd-resolved
  #  down-pre

  # Enable istio support for openvpn connections
  istio:
    enabled: false
    proxy:
      port: 15001
  iptablesExtra: []
  # - -A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
  # - -A FORWARD -m conntrack --ctstate NEW -d 10.240.0.0/255.255.0.0 -j ACCEPT
  # - -A FORWARD -j REJECT

  # Enable CCD support
  ccd:
    enabled: true
    config: {
            kh-pod-gw: "ifconfig-push 192.168.72.90 255.255.255.0\niroute 172.22.0.0 255.255.255.0\n"
             }

nodeSelector: {}
tolerations: []

